services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: ai_doc_postgres
    environment:
      POSTGRES_DB: ai_doc
      POSTGRES_USER: root
      POSTGRES_PASSWORD: yashnirjala24
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d ai_doc"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ai_doc_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data: