spring.application.name=AI_Document_Assistant
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile
spring.ai.openai.chat.options.temperature=0.2
spring.ai.openai.chat.options.max-tokens=200

#db configurations
#spring.datasource.url=document_memory
#spring.datasource.username=root
#spring.datasource.password=yashnirjala24
#spring.ai.chat.memory.repository.jdbc.initialize-schema=always
