spring.application.name=AI_Document_Assistant
spring.datasource.driver-class-name=org.postgresql.Driver
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini-2024-07-18
spring.ai.openai.embedding.options.model=text-embedding-3-small

spring.ai.openai.chat.options.temperature=0.2
spring.ai.openai.chat.options.max-tokens=1000
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_doc
spring.ai.chat.memory.repository.jdbc.initialize-schema=always
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
logging.level.org.springframework.security=ERROR
# pgvector
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=1536

#jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Max size permitted for each individual file
spring.servlet.multipart.max-file-size=10MB

# Max request size allowed for the entire multipart/form-data request
spring.servlet.multipart.max-request-size=10MB